# ===================== GAME =====================
BOARD_SIZE = 17
SQUARE_SIZE = 50
FPS = 10

# ===================== ACTIONS =====================
ACTION_UP = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTIONS = [ACTION_UP, ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT]

# ===================== REWARDS =====================
REWARD_WIN = 10
REWARD_LOSE = -10
REWARD_CLOSER = 0.1
REWARD_FARTHER = -0.2
REWARD_EAT = 10

# ===================== DQN ARCHITECTURE =====================
CONV1_IN_CHANNELS = 1
CONV1_OUT_CHANNELS = 32
CONV2_IN_CHANNELS = 32
CONV2_OUT_CHANNELS = 64
CONV3_IN_CHANNELS = 64
CONV3_OUT_CHANNELS = 64
CONV_KERNEL_SIZE = 3
CONV_STRIDE = 1
CONV_PADDING = 1
FC_INPUT_SIZE = CONV3_OUT_CHANNELS * BOARD_SIZE * BOARD_SIZE
FC_HIDDEN_SIZE = 256
OUTPUT_SIZE = 4
GAMMA = 0.99

# ===================== EPSILON GREEDY =====================
EPSILON_START = 1
EPSILON_FINAL = 0.05
EPSILON_DECAY = 400

# ===================== TRAINING =====================
MIN_BUFFER_SIZE = 1000
BATCH_SIZE = 128
LEARNING_RATE = 0.001
EPOCHS = 200000
START_EPOCH = 0
TARGET_UPDATE_FREQ = 20
SCHEDULER_MILESTONES = [5000, 10000, 20000]
SCHEDULER_GAMMA = 0.5
LOG_INTERVAL = 10
MAX_STEPS_WITHOUT_EAT = 500

# ===================== REPLAY BUFFER =====================
BUFFER_CAPACITY = 500000

# ===================== BOMB =====================
BOMB_MIN_DISTANCE = 2
BOMB_TIMER_SECONDS = 3
BOMB_COOLDOWN = 3
BOMB_SPAWN_PROBABILITY = 0.015
SECOND_SCREEN_SCORE = 10

# ===================== SNAKE / MOUSE INIT =====================
SNAKE_INIT_MIN = 4
SNAKE_INIT_MAX = 12
MOUSE_INIT_MIN = 1
MOUSE_INIT_MAX = 15

# ===================== COLORS =====================
COLOR_BLUE = (137, 168, 178)
COLOR_LIGHTBLUE = (179, 200, 207)
COLOR_DARK_BROWN = (175, 143, 111)
COLOR_LIGHT_BROWN = (209, 187, 158)
COLOR_PINK = (255, 205, 201)
COLOR_LIGHT_PINK = (253, 172, 172)
COLOR_WHITE = (255, 255, 255)
COLOR_BOMB_AREA = (255, 0, 0, 60)
COLOR_BOMB_OUTER = (180, 0, 0)
COLOR_BOMB_INNER = (255, 200, 200)
COLOR_EXIT_BUTTON = (218, 108, 108)
COLOR_EXIT_BUTTON_HOVER = (205, 86, 86)

# ===================== FONTS =====================
FONT_PATH = "Fonts/FunnyKids.otf"
FONT_SIZE = 36
FONT_SIZE_SMALL = 18
FONT_SIZE_LARGE = 50

# ===================== UI =====================
OVERLAY_OPACITY = 180
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_BORDER_RADIUS = 10
BUTTON_BORDER_WIDTH = 3
SCORE_POSITION = (10, 10)
